### PR TITLE
Sentence likelihood scores

### PR DESCRIPTION
**Pull request by mataddy**
@piskvorky and @gojomo this is an updated pull request, per our discussion back in #303, for the likelihood scoring used in http://arxiv.org/abs/1504.07295.

Things mostly mirror your 'train' functions. 

The functions don't exist for negative sampling trained models.  As @gojomo and I briefly discussed, one could figure out an analogue score for negative sampling.  However, I'm not super motivated to do so unless you guys want it... the HS scheme makes a lot more sense in this context.

### CODE REVIEW

**Comment by piskvorky** [comment]
@mataddy looks good, let's merge! Can you rebase/merge against develop?

We've merged @gojomo's doc2vec refactor, so the PR is no longer auto-merge. It looks clean and focused though, so whatever conflicts there, they should be trivial.

Cheers! (we're looking to make a new gensim release this weekend -- would be great if this could make it in)

**Comment by mataddy** [comment]
@piskvorky super cool.  I just merged and fixed a few small conflicts; things look nice and I re-ran my notebooks to confirm nothing changes.

merge at will; I'm stoked to have contributed a tiny little bit to gensim!

**Comment by piskvorky** [comment]
@cscorley @gojomo are we good to merge?

**Comment by mataddy** [comment]
hey @piskvorky you're latest commit created a small conflict that I've fixed; should be good to go again now.

**Comment by piskvorky** [comment]
Brilliant, merging.

Thanks again Matt for the clean & useful PR!

**Comment by piskvorky** [comment]
By the way, any chance we could see a tutorial?

Or can you extend the notebook you showed earlier with more background & motivation, so we can commit that into gensim as well, to serve as a more noob-friendly tutorial on how to use the scoring?

**Comment by mataddy** [comment]
yes, for sure.  I'm running off to catch a plane right now so won't be able to get it into your release this weekend, but I will definitely put together a tutorial before I present at ACL at end of month (and advertise to users there).  

great working with you guys!

**Comment by piskvorky** [comment]
Best of luck at ACL, have a safe flight :)

**Pull request merged**
