### PR TITLE
Fixed minor doc typo.

### PR DESCRIPTION
**Pull request by pombredanne**
I ran a quick experiment and this word was most similar to LGPL ;)
Happy new year!

### CODE REVIEW

**Comment by piskvorky** [comment]
Good catch, thanks :)

**Comment by piskvorky** [comment]
@tmylk all tests seem to be failing, what's going on?

**Comment by pombredanne** [comment]
@piskvorky I swear it was not me.

**Comment by gojomo** [comment]
Many tests failing with same smart_open "NotImplementedError: unknown file mode wb+"  issue recently reported to list (https://groups.google.com/d/msg/gensim/MTEqJwvLs08/kh8TKm9xBAAJ) and mentioned elsewhere. So probably an issue with some other library/package-manager changing. 

Might something in the 13-days-ago smart_open 1.3.1 release have broken? Might there be a version conflict with conda using a wrong or older package somewhere?

**Comment by gojomo** [comment]
Same issue as https://github.com/piskvorky/smart_open/issues/49

**Comment by piskvorky** [comment]
@tmylk this is serious enough to warrant an immediate fix and re-release (of smart_open).

**Comment by tmylk** [comment]
Build passing now

**Pull request merged**
