### PR TITLE
Preliminary attempt to create a conda recipe for gensim

### PR DESCRIPTION
**Pull request by ijstokes**
This is work-in-progress. It needs to be fixed and a cross-platform build configuration .anaconda.yml needs to be added. The conda package will eventually be found here:

https://anaconda.org/ijstokes/gensim

however I can't get it to build correctly at the moment.

### CODE REVIEW

**Comment by ijstokes** [comment]
@ilanschnell if you could provide your insights, I'd appreciate it.  This PR shows the conda recipe I'm trying to build.  It relies on three conda packages I've independently built: Pyro4, Serpent, smart_open, all of which are in my Anaconda Cloud channel.  The first two I created PRs for, while the third I used the existing recipe I grabbed from the `http://anaconda.org/ioos` organization and re-built the package with `--python 3.4` then put it in my own channel.

Serpent:
* https://github.com/irmen/Serpent/pull/13
* https://anaconda.org/ijstokes/serpent

Pyro4:
* https://github.com/irmen/Pyro4/pull/93
* https://anaconda.org/ijstokes/pyro4

smart_open:
* https://anaconda.org/ijstokes/smart_open

But then when I try to build, things fail with `smart_open` which somehow is being fetched from PyPI instead of from a conda package which it should be able to find in my `ijstokes` channel.

```bash
$ conda build --python 3.4 -c ijstokes conda.recipe
Removing old build environment
Removing old work directory
BUILD START: gensim-0.12.3-py34_1
Fetching package metadata: ............
Solving package specifications: ............
The following NEW packages will be INSTALLED:

    numpy:      1.10.1-py34_0
    openssl:    1.0.2d-0     
    pip:        7.1.2-py34_0 
    pyro4:      4.40-py34_1  
    python:     3.4.3-2      
    readline:   6.2-2        
    serpent:    1.12-py34_1  
    setuptools: 18.4-py34_0  
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.26.0-py34_1
    xz:         5.0.5-0      
    zlib:       1.2.8-0      

Linking packages ...
[      COMPLETE      ]|#################################################################################################| 100%
Removing old work directory
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
From github.com:ijstokes/gensim
 * [new branch]      conda_recipe -> conda_recipe
checkout: u'0.12.3'
Cloning into '/Users/ijstokes/anaconda/conda-bld/work'...
done.
Note: checking out '0.12.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 280a488... Merge branch 'release-0.12.3'
==> git log -n1 <==

commit 280a488cd688ef8c58b823f4845169e925bda708
Merge: 1c63c9a f2bddb6
Author: tmylk <lev.konst@gmail.com>
Date:   Fri Nov 6 14:38:28 2015 +0000

    Merge branch 'release-0.12.3'


==> git describe --tags --dirty <==

0.12.3


==> git status <==

HEAD detached at 0.12.3
nothing to commit, working directory clean


Package: gensim-0.12.3-py34_1
source tree in: /Users/ijstokes/anaconda/conda-bld/work
+ /Users/ijstokes/anaconda/envs/_build/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating gensim.egg-info
writing dependency_links to gensim.egg-info/dependency_links.txt
writing top-level names to gensim.egg-info/top_level.txt
writing gensim.egg-info/PKG-INFO
writing requirements to gensim.egg-info/requires.txt
writing manifest file 'gensim.egg-info/SOURCES.txt'
reading manifest file 'gensim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.sh' under directory '.'
writing manifest file 'gensim.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-3.4
creating build/lib.macosx-10.5-x86_64-3.4/gensim
copying gensim/__init__.py -> build/lib.macosx-10.5-x86_64-3.4/gensim

[THEN LOTS OF COPYING OF gensim/* -> build/lib.macosx-10.5-x86_64-3.4 ]

running build_ext
building 'gensim.models.word2vec_inner' extension
creating build/temp.macosx-10.5-x86_64-3.4
creating build/temp.macosx-10.5-x86_64-3.4/gensim
creating build/temp.macosx-10.5-x86_64-3.4/gensim/models
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Igensim/models -I/Users/ijstokes/anaconda/envs/_build/include/python3.4m -I/Users/ijstokes/anaconda/envs/_build/lib/python3.4/site-packages/numpy/core/include -c ./gensim/models/word2vec_inner.c -o build/temp.macosx-10.5-x86_64-3.4/./gensim/models/word2vec_inner.o

[ THEN LOTS OF COMPILE TIME WARNINGS ]

38 warnings generated.
gcc -bundle -undefined dynamic_lookup -L/Users/ijstokes/anaconda/envs/_build/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.4/./gensim/models/doc2vec_inner.o -L/Users/ijstokes/anaconda/envs/_build/lib -o build/lib.macosx-10.5-x86_64-3.4/gensim/models/doc2vec_inner.so
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/gensim
copying build/lib.macosx-10.5-x86_64-3.4/gensim/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/gensim
creating build/bdist.macosx-10.5-x86_64/egg/gensim/corpora
copying build/lib.macosx-10.5-x86_64-3.4/gensim/corpora/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/gensim/corpora

[ THEN LOTS MORE COPYING FROM build/lib.macosx- -> build/bdist.macosx- ]

byte-compiling build/bdist.macosx-10.5-x86_64/egg/gensim/utils.py to utils.cpython-34.pyc
creating stub loader for gensim/models/word2vec_inner.so
creating stub loader for gensim/models/doc2vec_inner.so
byte-compiling build/bdist.macosx-10.5-x86_64/egg/gensim/models/word2vec_inner.py to word2vec_inner.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/gensim/models/doc2vec_inner.py to doc2vec_inner.cpython-34.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying gensim.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying gensim.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying gensim.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying gensim.egg-info/not-zip-safe -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying gensim.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying gensim.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/gensim-0.12.3rc1-py3.4-macosx-10.5-x86_64.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing gensim-0.12.3rc1-py3.4-macosx-10.5-x86_64.egg
creating /Users/ijstokes/anaconda/envs/_build/lib/python3.4/site-packages/gensim-0.12.3rc1-py3.4-macosx-10.5-x86_64.egg
Extracting gensim-0.12.3rc1-py3.4-macosx-10.5-x86_64.egg to /Users/ijstokes/anaconda/envs/_build/lib/python3.4/site-packages
Adding gensim 0.12.3rc1 to easy-install.pth file

Installed /Users/ijstokes/anaconda/envs/_build/lib/python3.4/site-packages/gensim-0.12.3rc1-py3.4-macosx-10.5-x86_64.egg
Processing dependencies for gensim==0.12.3rc1
Searching for smart-open>=1.2.1
Traceback (most recent call last):
  File "setup.py", line 178, in <module>
    include_package_data=True,
  File "/Users/ijstokes/anaconda/envs/_build/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/ijstokes/anaconda/envs/_build/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/ijstokes/anaconda/envs/_build/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ijstokes/anaconda/envs/_build/lib/python3.4/site-packages/setuptools-18.4-py3.4.egg/setuptools/command/install.py", line 67, in run

[ SETUPTOOLS STACKTRACE YADA YADA ]

  File "/Users/ijstokes/anaconda/envs/_build/lib/python3.4/site-packages/setuptools-18.4-py3.4.egg/setuptools/package_index.py", line 283, in process_url

RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/smart_open/r

Command failed: /bin/bash -x -e /Users/ijstokes/code/gensim/conda.recipe/build.sh

```

**Comment by ijstokes** [comment]
OK, fixed. That was very n00b of me: was simply missing the build-time `smart_open` (and others) dependencies.  gensim can now be installed with:

```
conda install -c ijstokes gensim
```

if you are on OS X and with Python 3.4.  All others will have to wait or offer an Anaconda Cloud cross-python-version and cross platform build descriptor `.anaconda.yml` file.

Can also create a stand-alone gensim environment on OS X with:

```bash
conda create -n gensim -c ijstokes gensim python=3.4
```

**Comment by piskvorky** [comment]
Interesting! I don't know much about conda recipes, but if it helps gensim users, I'm +1 on including this.

If I understand correctly, this will make gensim easier to install for users that use Anaconda, right? Are there any additional steps we (gensim devs, CC @tmylk ) have to follow to make this a reality?

From what I remember, there is already (some version of) gensim in Anaconda -- how is this different? We probably want a single authoritative version, to avoid confusion.

Cheers!

**Comment by tmylk** [comment]
For completeness, link to discussion on Anaconda mailing list https://groups.google.com/a/continuum.io/forum/#!searchin/anaconda/gensim/anaconda/tZdjFMebrAo/gDGRS7NDEQAJ

**Comment by piskvorky** [comment]
@ijstokes @tmylk is the ready to merge or do we need something else?

A few words on how this helps / is going to be used, would still be welcome.

**Comment by piskvorky** [comment]
@ijstokes @tmylk ping. Is this ready to merge, what else is needed?

**Comment by piskvorky** [comment]
@tmylk finish this PR, one way or another.

**Comment by tmylk** [comment]
@ljstokes, thanks! 0.12.2 is in Anaconda list of packages for Python 3 so this doesn't seem to be necessary. 
http://docs.continuum.io/anaconda/pkg-docs

**Pull request closed without merging**
