### PR TITLE
Added DTM example notebook

### PR DESCRIPTION
**Pull request by Arttii**
Hi,

Finally got around to doing this. I applied some pep8 to this and rearranged some stuff. Tell me if we need to change anything else.

Artyom

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks @Arttii !

`The example dataset is already processed into list of tokens.`

What "the" dataset? I don't see any dataset anywhere -- what am I missing?

It would be more instructive to show what kind of input DTM accepts. It looks like the notebook unpickles some file from local disk (?) now, but I (the user) still have no idea what that is.

Can you think of a way to make this clearer?

**Comment by Arttii** [comment]
Ya it just basically loads up a normal gensim corpus + a time sequence array. Do you think embedding the pickled file inside the notebook will make it more clear? Its like basically an list of lists.

**Comment by piskvorky** [comment]
Yes, much better, thanks :)

I can't see any output for the last three notebook cells though -- is that on purpose?

@tmylk can you help @Arttii with cleaning up this PR? Cheers.

**Comment by tmylk** [comment]
Hey @Arttii , thanks for this. I ran it on my Fedora Linux no problem. 
Some minor corrections in this version. If you are ok with them then please add to this PR https://github.com/piskvorky/gensim/blob/9c8e784d7a280744312751b3c9b41611798b49d1/docs/notebooks/dtm_example.ipynb

**Comment by piskvorky** [comment]
@tmylk still some typos ("defentiion") and PEP8 nitpicks (space after comma, line break around `DTM_HOME`), but it's looking up! Almost ready for merge.

Btw I've seen a [message on the mailing list](https://groups.google.com/d/msg/gensim/A_qiR2NN6PE/qJ22fXjzBAAJ) that it doesn't work even with the `initialize_lda=True` hack.

@Arttii @tmylk I'd prefer to investigate and fix this thoroughly, before merging the tutorial.

**Comment by tmylk** [comment]
Unfortunately I couldn't reproduce @deakkon's mailing list issue on my Linux box. 

The wrapper works well for me on Linux.

PEP8 and spelling updated in:
https://github.com/piskvorky/gensim/blob/Arttii-develop/docs/notebooks/dtm_example.ipynb

**Comment by Arttii** [comment]
I'll have you to check that. Sorry haven't had time recently. I'll take a look tomorrow maybe.
________________________________

**Comment by tmylk** [comment]
Hey @Arttii, is this ok to merge?
In PR #476 I added error forwarding via subprocess.check_output to DTM and Mallet wrappers so there would be less mailing list queries in the future.

**Comment by Arttii** [comment]
Hi,

Looks good. Sorry I didn't help out more some hectic work stuff.

Artyom
________________________________

**Comment by tmylk** [comment]
@Arttii Thanks a lot for adding the DTM wrapper! It seems to be used by a lot of people now.

**Pull request merged**
