### PR TITLE
fixes issue #352 in phrases.py

### PR DESCRIPTION
**Pull request by ikuyamada**
I think we don't need to check the presence of the last word in the vocabulary here.

### CODE REVIEW

**Comment by piskvorky** [comment]
@mfcabrera can you review & merge?

**Comment by mfcabrera** [comment]
@piskvorky  reviewed. It looks OK. but I cannot merge (need write access).

**Comment by piskvorky** [comment]
Ah, sorry. Added you as collaborator. 

Use the force wisely :)

**Comment by ikuyamada** [comment]
Thanks!

**Pull request merged**
