### PR TITLE
a single string label for LabeledSentence in doc2vec

### PR DESCRIPTION
**Pull request by zygmuntz**
...without wrapping in a sequence.

### CODE REVIEW

**Comment by cscorley** [comment]
I can be ok with this change.

ping @gojomo , what do you think? Will this change in your fork?

**Comment by cscorley** [comment]
By the way, @zygmuntz, can you squash this into a single commit, since it's fairly straightforward?

**Comment by piskvorky** [comment]
@cscorley What fork?

This is fine by me, +1.

Also, +1 on commit squash before merging. Thanks!

**Comment by zygmuntz** [comment]
Since I'm mostly unfamiliar with `rebase`, I squashed them by brute force into https://github.com/piskvorky/gensim/pull/339, closing dis.

**Comment by gojomo** [comment]
I don't expect any problems from this small convenience change (auto-tupling a single string passed to the LabeledSentence constructor). I'm trying to maintain the option of multiple-labels-per-doc, both because it might be important to the original Doc2Vec author @temerick, and I can envision some interesting potential uses (like one of the slots identifying an author). But in practice I've only been testing with a single label per doc. 

@piskvorky – @cscorley likely just means my working fork.

**Comment by cscorley** [comment]
Okay, thanks! I'll merge in the other PR.

**Pull request closed without merging**
