### PR TITLE
Rebasing #625

### PR DESCRIPTION
**Pull request by manasRK**
Rebasing #625. @tmylk 

I will close the older PR if necessary. Sorry for the trouble.

### CODE REVIEW

**Comment by manasRK** [comment]
@tmylk Does this look okay?

**Comment by piskvorky** [comment]
@tmylk don't forget to re-apply the (few) doc fixes in `word2vec_standalone` from #625. As a separate commit, if not part of this PR.

**Comment by manasRK** [comment]
@piskvorky adding the file in this commit.

**Comment by piskvorky** [comment]
Thanks, but these changes don't look correct. Please revert the commit and leave it to @tmylk .

**Comment by manasRK** [comment]
@tmylk I have rebased and updated changes. Any more stuff needed from my end?

**Comment by tmylk** [comment]
Merged in https://github.com/piskvorky/gensim/commit/982dc3c39f39479084072456f54a4feb2fcdc068

**Pull request closed without merging**
