### PR TITLE
add similar by word and vector

### PR DESCRIPTION
**Pull request by isohyt**
Related to Issue #381 
I added `similar_by_word()` and `similar_by_vector()`
We can use these functions as follows.

trained_model.similar_by_word('graph')
      [('user', 0.9999163150787354), ...]

trained_model.similar_by_vector([1,2])
      [('survey', 0.9942699074745178), ...]

### CODE REVIEW

**Comment by piskvorky** [comment]
-1, too much code duplication. These would be better served as simple wrappers, calling `most_similar` internally.

**Comment by isohyt** [comment]
I see.
I re-wrote simple wrappers, but both are almost the same.

**Comment by tmylk** [comment]
The two methods are exactly the same. Do the tests pass on your machine? 

A specific test can be run on your local machine with ``python setup.py test -m your.package.tests.test_module ``

**Comment by isohyt** [comment]
Yes, and also passed Travis-ci (https://travis-ci.org/isohyt/gensim/builds/120849620).
But it is not reflected in this PR.

Anyway, I cannot figure out what should I do...

**Comment by tmylk** [comment]
Thanks for the PR!
Merged in https://github.com/piskvorky/gensim/commit/b99e8528594b0898aa629f01be0919a18f25f190

**Pull request closed without merging**
