### PR TITLE
fix scoring without __prepare_items, add unit test

### PR DESCRIPTION
**Pull request by mataddy**
This fixes the problems pointed out in #407, which occurred due to a refactoring of the Train methods.

I went through the new train methods and adapted things related to score() accordingly.  Re-running my standard yelp example looks fine: http://nbviewer.ipython.org/github/taddylab/deepir/blob/master/deepir.ipynb

Also added a testScoring() so that we won't be suprised by this type of thing again.

Thanks!

### CODE REVIEW

**Comment by piskvorky** [comment]
Alright! The test is rather superficial, but it will do for now :)

Merging. Thanks @mataddy !

**Comment by mataddy** [comment]
no prob, thank you.  yep, the test is a bit cheeky I'll update it I promise ;-)

**Comment by gojomo** [comment]
That test would have saved me from inadvertently breaking this – sorry! – so it's a great start in my view. :)

**Comment by mataddy** [comment]
hi @piskvorky, sorry for the long delay but there is finally a more introductory demo up at https://github.com/TaddyLab/deepir/blob/master/deepir.ipynb.  the `docprob` wrapper function in the demo is something I could add to gensim if you're into it.

**Comment by piskvorky** [comment]
Looks nice, thanks Matt!

Do we integrate this notebook into the [docs/notebooks](https://github.com/piskvorky/gensim/tree/develop/docs/notebooks) directory of gensim, or just link to it somehow?

I won't have time to review in detail until November; CC @tmylk.

**Comment by mataddy** [comment]
great idea; so long as those docs/notebooks aren't run when the project is built this will work great.  I'll create a pull request with it and ping @tmylk

**Comment by gojomo** [comment]
Hmm, testing the notebooks each build is an interesting idea... but for now, they're not being run/tested every build.

**Comment by mataddy** [comment]
cool, thanks @gojomo. FYI the only reason it wouldn't work for my notebook here is because the data is on kaggle and the user needs to sign-up to get it.  but that could be worked around later if you guys decide to change policies and run the notebooks at each build

**Pull request merged**
