### PR TITLE
add sample wikidump file and some minimal tests

### PR DESCRIPTION
**Pull request by jonmcoe**
took this file https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles1.xml-p000000010p000030302.bz2 and trimmed it

wrote some (very) minimal tests

Addresses this issue: https://github.com/piskvorky/gensim/issues/650

### CODE REVIEW

**Comment by tmylk** [comment]
@jonmcoe Thanks a lot for a great start on #650 !

Python 2.6 build hangs on `wiki_corpus.get_texts` - not sure if it happens before or during assertions. Do you have any ideas about this?

**Comment by jonmcoe** [comment]
Yes I see that in the Travis now. I think that's during the actual   execution,  before the assertions. Will dig in a bit when I get back to computer. 

Are we sure the function runs to completion in 2.6 at all? Possible it just went unnoticed before the tests

**Comment by piskvorky** [comment]
@tmylk what is the answer? I'm curious too.

**Comment by jonmcoe** [comment]
@piskvorky i had a hard time getting anything to work on 2.6 (tho its obviously possible, as travis demonstrates) so i'm no help for you on that question

**Pull request merged**
