### PR TITLE
Deep IR tutorial notebook with yelp data

### PR DESCRIPTION
**Pull request by mataddy**
@tmylk @piskvorky  follow up on #417 I've added a demo for document classification via the Word2Vec.score function.

### CODE REVIEW

**Comment by mataddy** [comment]
added the fix requested in #470 and updated help

**Comment by mataddy** [comment]
just adding some extra checks to avoid issues total_sentences is not set properly as in #470

**Comment by mataddy** [comment]
this should all be good to go

**Comment by piskvorky** [comment]
Looks good @mataddy ! Thanks a lot for the clean up and PR, merging.

**Comment by mataddy** [comment]
Happy to help; gensim is a blast!

**Comment by mataddy** [comment]
hey @piskvorky I noticed this didn't merge?  let me know if anything came up that you need me to fix.

**Comment by piskvorky** [comment]
Leaving the merge for @tmylk , nothing else to be done from my POW.

**Comment by piskvorky** [comment]
@tmylk this deserves a tweet from `@gensim_py` too :)

**Comment by tmylk** [comment]
Oh yeah. Tweet done.

**Comment by mataddy** [comment]
awesome, thanks guys!

**Pull request merged**
