### PR TITLE
allow int/string type doc2vec tag

### PR DESCRIPTION
**Pull request by isohyt**
Allow calls like TaggedDocument(words=words,tags='SENT_99'), as a shorthand for TaggedDocument(words=words,tags=['SENT_99'])

### CODE REVIEW

**Comment by tmylk** [comment]
@isohyt Thanks for the PR

Is it a fix for https://github.com/piskvorky/gensim/issues/381 ?

Please add new tests and a note in CHANGELOG.

**Comment by gojomo** [comment]
Mixed feelings about this sort of special-casing: may hide functionality (multiple tags), saves just two characters. But also may turn a common-error into something that does-what-was-expected. If done for strings, should be done for ints too.

**Comment by isohyt** [comment]
@tmylk, thank you for your comment.
I'm writing doc2vec documentation and I bumped into this problem.
So I fixed this doc2vec tag issue.

I also have a plan to fix for issue #381.

**Comment by isohyt** [comment]
@gojomo, thank you for your comment.
I added for int type tags feature.

**Comment by isohyt** [comment]
I overlooked some problems. I'm fixing now.

**Comment by isohyt** [comment]
Hmm...
It goes will in my local environment, but I have no idea to test this proposed code.
Should I rewrite TaggedDocument from scratch without namedtuple to add this feature??

**Comment by isohyt** [comment]
I found the essential mistake, so I close this PR.
I want to try to add this feature from a different approach in the later.

**Pull request closed without merging**
