### PR TITLE
Rebase of "online word2vec" by rutum

### PR DESCRIPTION
**Pull request by zachmayer**
I rebased https://github.com/piskvorky/gensim/pull/435 off the develop branch, and fixed merge conflicts.  I think this branch has all the new features from the  "online word2vec" and I've resolved all the merge conflicts and removed the commits from master.

@rutum Let me know if I missed anything.  You could pull this branch, and then work from here to respond to the issues on your pull request.

Full list of commits from original PR below:
recovering lost work
updating bug in sentences iterator
vector freeze after each training iteration
cbow update
clean up code
update summarization tutorial image
resolving merge conflicts
resolving merge conflicts
resolving merge conflicts
resolving merge conflicts
resolving merge conflicts
resolving merge conflicts
update_weights function change
updating the numpy copy code
updating the numpy copy code

### CODE REVIEW

**Comment by zachmayer** [comment]
I get a few test failures when I run locally:
```{python}
======================================================================
ERROR: testOnlineLearning (gensim.test.test_word2vec.TestWord2VecModel)
Test that the algorithm is able to add new words to the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zachary/source/gensim/gensim/test/test_word2vec.py", line 104, in testOnlineLearning
    model.build_vocab(new_sentences, update=True)
  File "/Users/zachary/source/gensim/gensim/models/word2vec.py", line 510, in build_vocab
    self.finalize_vocab(update)  # build tables & arrays
  File "/Users/zachary/source/gensim/gensim/models/word2vec.py", line 649, in finalize_vocab
    self.sort_vocab()
  File "/Users/zachary/source/gensim/gensim/models/word2vec.py", line 672, in sort_vocab
    raise RuntimeError("must sort before initializing vectors/weights")
RuntimeError: must sort before initializing vectors/weights

======================================================================
FAIL: test_text_keywords (gensim.test.test_keywords.TestKeywordsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zachary/source/gensim/gensim/test/test_keywords.py", line 39, in test_text_keywords
    self.assertEqual(set(map(str, generated_keywords)), set(map(str, kw)))
AssertionError: Items in the first set but not the second:
'southeast'
'defense'
'winds heavy'
Items in the second set but not the first:
'domingo'
'people'
'defense alerted'
'alert'
'pushed'
'cabral said'
'winds'
'associated'
'residents'
'south'

======================================================================
FAIL: test_text_keywords_pos (gensim.test.test_keywords.TestKeywordsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zachary/source/gensim/gensim/test/test_keywords.py", line 65, in test_text_keywords_pos
    self.assertEqual(set(map(str, generated_keywords_NNVBJJ)), set(map(str, kw)))
AssertionError: Items in the first set but not the second:
'gonzalez'
'press'
'service'
Items in the second set but not the first:
'domingo'
'san'
'juan'
'pushed'
'miles'
'south'
'dominican'

======================================================================
FAIL: test_text_keywords_words (gensim.test.test_keywords.TestKeywordsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zachary/source/gensim/gensim/test/test_keywords.py", line 50, in test_text_keywords_words
    self.assertEqual(len(generated_keywords), 16)
AssertionError: 15 != 16

----------------------------------------------------------------------
Ran 267 tests in 1452.073s

FAILED (failures=3, errors=1, skipped=8)
```

**Comment by zachmayer** [comment]
Hmmm still getting some test failures.  I'll attempt to fix them.

**Comment by zachmayer** [comment]
I'm going to take a look at the test failure, but may need some help fixing it:
```{python}
======================================================================
ERROR: testOnlineLearning (gensim.test.test_word2vec.TestWord2VecModel)
Test that the algorithm is able to add new words to the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/piskvorky/gensim/gensim/test/test_word2vec.py", line 104, in testOnlineLearning
    model.build_vocab(new_sentences, update=True)
  File "/home/travis/build/piskvorky/gensim/gensim/models/word2vec.py", line 510, in build_vocab
    self.finalize_vocab(update)  # build tables & arrays
  File "/home/travis/build/piskvorky/gensim/gensim/models/word2vec.py", line 649, in finalize_vocab
    self.sort_vocab()
  File "/home/travis/build/piskvorky/gensim/gensim/models/word2vec.py", line 672, in sort_vocab
    raise RuntimeError("must sort before initializing vectors/weights")
RuntimeError: must sort before initializing vectors/weights
```

**Comment by zachmayer** [comment]
Ahh, I see.  I need to add the update parameter to `sort_vocab`.

**Comment by zachmayer** [comment]
So I think the easy solution is to say you can't update models with sorted vocab.

The other solution might be to skip the sorting step when updating a sorted model.

**Comment by zachmayer** [comment]
I added 2 commits, one that fixed the test to use non-sorted vocab, and a second commit to skip sorting when updating a sorted model.

Let me know which way makes sense.

**Comment by zachmayer** [comment]
Travis passes now, but appveyor fails

**Comment by zachmayer** [comment]
Can someone help me with the appveyor failure?  I'm not sure what went wrong.

I could also use some help deciding how to handle `sort_vocab` when updating models.

**Comment by zachmayer** [comment]
appveyor error is 
```{python}
Collecting gensim
  Could not find a version that satisfies the requirement gensim (from versions: )
No matching distribution found for gensim
Command exited with code 1
```

**Comment by piskvorky** [comment]
CCing @tmylk for AppVeyor. If it constantly fails, isn't it better to just drop it? It's confusing for everybody.

**Comment by zachmayer** [comment]
@piskvorky How do I re-run the appveyor checks?

**Comment by piskvorky** [comment]
Not sure -- that's a question for @tmylk.

**Comment by phdowling** [comment]
@piskvorky regarding AppVeyor: We could also just try https://github.com/The-Compiler/pytest-vw

**Comment by zachmayer** [comment]
@piskvorky @phdowling I rebased against the develop branch again, which will re-trigger the travis tests.  It looks like other PRs are passing now, so I expect this one will too (but we'll see).

**Comment by zachmayer** [comment]
@piskvorky @phdowling tests passing now.

**Comment by gushecht** [comment]
Hey guys, maybe I made a mistake, but I:

1. Forked https://github.com/piskvorky/gensim
2. Cloned it locally
3. Updated my local files to include the changes in this PR
4. Ran `sudo python setup.py install`
5. Opened ipython and input `import gensim.models`

I got the following message:
```python
  File "/Applications/anaconda/lib/python2.7/site-packages/gensim-0.12.4-py2.7-macosx-10.5-x86_64.egg/gensim/models/word2vec.py", line 1022
    self.syn0[i] = self.seeded_vector(self.index2word[i] str(self.seed))
                                                           ^
SyntaxError: invalid syntax
```
Which I was able to resolve by opening the file raising the error and adding a comma between the arguments.

Not sure why this happened, but wanted to make you aware.

Tragically, when I train on text8-rest and then run `model.n_similarity(["king"], ["duke"])` I get -0.10245139651395152.

Any help would be greatly appreciated.  I'm going to try again starting fresh.

**Comment by zachmayer** [comment]
@gushecht I force pushed to this branch, which probably caused the error

**Comment by tmylk** [comment]
@zachmayer Thanks a lot for your work! This functionality is in high demand. Do you think it is ready to be reviewed and merged after the conflicts are resolved?

**Comment by zachmayer** [comment]
Definitly ready for review!  I'll rebase and resolve merge conflicts (I already did it once lol)

**Comment by zachmayer** [comment]
Rebased it here: https://github.com/piskvorky/gensim/pull/700

**Pull request closed without merging**
