### PR TITLE
Make show_topics more consistent across models

### PR DESCRIPTION
**Pull request by cscorley**
This PR contains changes to address issues #354 and #389. Note that this change breaks compatibility for anyone that has come to rely on the format for a particular model.

Additional changes include splitting up the increasingly growing test_models.py file into individual files :)

### CODE REVIEW

**Comment by cscorley** [comment]
FYI, I think the latest numpy will make these tests failing (at least on my local Python 3 environment). Seems that, at least for `LdaModel`, that the index of numpy arrays will be `numpy.int64` and no longer `int`. There's also some deprecation warnings being thrown from numpy related to how `LdaModel` indexes into arrays.

**Comment by piskvorky** [comment]
Great! Can you also add a short summary to README, explaining whom this affects and how?

Re. failing tests: what's the problem with int64?

Indexing indexing: I know this one. It's due to [this line](https://github.com/piskvorky/gensim/blob/master/gensim/models/ldamodel.py#L559): that `as_numpy=True` forces `utils.grouper` to return documents as floats:

```python
doc = [(1, 0.5), (2, 0.3)]
print numpy.array(doc)

array([[ 1. ,  0.5],
       [ 2. ,  0.3]])
```

(the topic indexes become floats).

This was an optimization for sending data via Pyro, so that they serialize to smaller chunks. I think it's no longer needed => let's `as_numpy=False`.

**Comment by cscorley** [comment]
w.r.t., int64: It should be handled now in the test explicitly, but numpy was returning indexes as int in Python 2 while numpy.int64 in Python 3. Very strange.

**Comment by piskvorky** [comment]
@cscorley does this need anything else, or are we ready to merge? (after resolving the conflict)

**Comment by piskvorky** [comment]
@cscorley we'll make a new release again this week. Any chance we could get this in?

**Comment by cscorley** [comment]
Sorry @piskvorky, only really have the chance to work on weekends :) Luckily, the merge conflict was only in CHANGELOG.txt, so this should be ready to go.

**Comment by piskvorky** [comment]
Perfect, thanks.

@tmylk please review & merge. This is a major, breaking change, so we have to be very explicit about this change in the release notes / announcement!

Probably warrants a major version bump too.

**Comment by piskvorky** [comment]
@cscorley I see `as_numpy` is still True... is there a reason we don't want the indices to be integer? Or how did you handle this?

Possibly related to #494 .

**Comment by cscorley** [comment]
@piskvorky more or less, I didn't change it here because I don't know how that would affect the Pyro stuff, so I left it as is for this PR. No idea how to make a test for that, not familiar with Pyro at all.

**Comment by piskvorky** [comment]
Alright! Let's change it in a separate PR. It will affect Pyro performance (=will need more memory in the distributed computing), but that use case is so marginal I can't say I care much. Let's just mention in visibly in the CHANGELOG, for people who do use the distributed functionality.

Maybe we can even add this is an LDA parameter (default `as_numpy=False`), rather than hardwiring True/False there. That way, users can choose the value themselves.

@mattilyra are you up for this PR?

**Comment by mattilyra** [comment]
@piskvorky Yes I can take it. Having a parameter `as_numpy=False/True` for LDA isn't particularly clear though and needs a lot of explaining. Besides wouldn't `as_numpy=True` break (or generate a lot of warnings) for Pyro as well under Py3?

**Pull request merged**
