### PR TITLE
bug fix in wikicorpus

### PR DESCRIPTION
**Pull request by eiTanLaVi**

### CODE REVIEW

**Comment by cscorley** [comment]
In what cases does the original trigger a bug? Seems like it would be better to give any() a generator than to create an entire list first.

**Comment by eiTanLaVi** [comment]
testing it locally without the [] any always returned true, even when the
entire list was False

On Tue, Apr 21, 2015 at 4:50 PM, Christopher Corley <
notifications@github.com> wrote:

> In what cases does the original trigger a bug? Seems like it would be
> better to give any() a generator than to create an entire list first.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/piskvorky/gensim/pull/329#issuecomment-94798947>.
>



-- 

*eiTan LaVi*
*cell*: + 972 544 700 888
*fax*:  + 972 153 544 700 888

**Comment by cscorley** [comment]
On which Python version? I am unable to reproduce:

```python
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> any([False, False, False])
False
>>> any(False for x in range(10))
False
```

**Comment by eiTanLaVi** [comment]
2.7 anaconda (running ipython notebook)

On Tue, Apr 21, 2015 at 5:16 PM, Christopher Corley <
notifications@github.com> wrote:

> On which Python version? I am unable to reproduce:
>
> Python 2.7.9 (default, Dec 11 2014, 04:42:00)
> [GCC 4.9.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.>>> any([False, False, False])False>>> any(False for x in range(10))False
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/piskvorky/gensim/pull/329#issuecomment-94810893>.
>



-- 

*eiTan LaVi*
*cell*: + 972 544 700 888
*fax*:  + 972 153 544 700 888

**Comment by piskvorky** [comment]
Sounds like a bug in anaconda then, not gensim.

@eiTanLaVi can you post a minimum failing example + the exact traceback?

**Comment by piskvorky** [comment]
@eiTanLaVi ping

**Comment by piskvorky** [comment]
Closing as unrelated to gensim.

**Pull request closed without merging**
