### PR TITLE
[WIP] Clean up of FlsaModel: fixing bugs + formatting + efficiency

### LINKED ISSUE #3423: Unnecessary dependency on FuzzyTM pulls in many libraries
#### Problem description

I'm trying to upgrade to the new Gensim 4.3.0 release. My colleague @juhoinkinen noticed in https://github.com/NatLibFi/Annif/pull/660 that Gensim 4.3.0 pulls in more dependencies than the previous release 4.2.0, including pandas. I suspect that at least the FuzzyTM dependency (which in turn pulls in pandas) is actually unused and thus unnecessary.

#### Steps/code/corpus to reproduce

Installing Gensim 4.2.0 into an empty venv (only four packages installed):

```
$ pip install gensim==4.2.0
Collecting gensim==4.2.0
  Downloading gensim-4.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 2.0 MB/s eta 0:00:00
Collecting scipy>=0.18.1
  Downloading scipy-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 3.3 MB/s eta 0:00:00
Collecting numpy>=1.17.0
  Downloading numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 10.6 MB/s eta 0:00:00
Collecting smart-open>=1.8.1
  Downloading smart_open-6.3.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 KB 9.7 MB/s eta 0:00:00
Installing collected packages: smart-open, numpy, scipy, gensim
Successfully installed gensim-4.2.0 numpy-1.24.1 scipy-1.10.0 smart-open-6.3.0
```

Installing Gensim 4.3.0 into an empty venv (18 packages installed):

```
$ pip install gensim==4.3.0
Collecting gensim==4.3.0
  Downloading gensim-4.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 6.9 MB/s eta 0:00:00

[...skipping downloads...]

Installing collected packages: pytz, urllib3, smart-open, six, numpy, idna, charset-normalizer, certifi, scipy, requests, python-dateutil, simpful, pandas, miniful, fst-pso, pyfume, FuzzyTM, gensim
  Running setup.py install for miniful ... done
  Running setup.py install for fst-pso ... done
Successfully installed FuzzyTM-2.0.5 certifi-2022.12.7 charset-normalizer-2.1.1 fst-pso-1.8.1 gensim-4.3.0 idna-3.4 miniful-0.0.6 numpy-1.24.1 pandas-1.5.2 pyfume-0.2.25 python-dateutil-2.8.2 pytz-2022.7 requests-2.28.1 scipy-1.10.0 simpful-2.9.0 six-1.16.0 smart-open-6.3.0 urllib3-1.26.13
```

The size of the venv has grown from 249MB to 318MB, an increase of 69MB.

Here is what `pipdeptree` shows - FuzzyTM appears to be the main reason why so many libraries are pulled in:

```
gensim==4.3.0
  - FuzzyTM [required: >=0.4.0, installed: 2.0.5]
    - numpy [required: Any, installed: 1.24.1]
    - pandas [required: Any, installed: 1.5.2]
      - numpy [required: >=1.21.0, installed: 1.24.1]
      - python-dateutil [required: >=2.8.1, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - pytz [required: >=2020.1, installed: 2022.7]
    - pyfume [required: Any, installed: 0.2.25]
      - fst-pso [required: Any, installed: 1.8.1]
        - miniful [required: Any, installed: 0.0.6]
          - numpy [required: >=1.12.0, installed: 1.24.1]
          - scipy [required: >=1.0.0, installed: 1.10.0]
            - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
        - numpy [required: Any, installed: 1.24.1]
      - numpy [required: Any, installed: 1.24.1]
      - scipy [required: Any, installed: 1.10.0]
        - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
      - simpful [required: Any, installed: 2.9.0]
        - numpy [required: >=1.12.0, installed: 1.24.1]
        - requests [required: Any, installed: 2.28.1]
          - certifi [required: >=2017.4.17, installed: 2022.12.7]
          - charset-normalizer [required: >=2,<3, installed: 2.1.1]
          - idna [required: >=2.5,<4, installed: 3.4]
          - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.13]
        - scipy [required: >=1.0.0, installed: 1.10.0]
          - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
    - scipy [required: Any, installed: 1.10.0]
      - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
  - numpy [required: >=1.18.5, installed: 1.24.1]
  - scipy [required: >=1.7.0, installed: 1.10.0]
    - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
  - smart-open [required: >=1.8.1, installed: 6.3.0]
pip==22.0.2
pipdeptree==2.3.3
setuptools==59.6.0
```

It appears that the FuzzyTM dependency was added in PR #3398 (Flsamodel) by @ERijck . The first commits in this PR depended on the library, but a subsequent commit 9fec00b32d281e795f3b4701bf11fa1c97780227 reworked the code so it doesn't need to import FuzzyTM at all. But the dependency in setup.py wasn't actually removed, it's still there: https://github.com/RaRe-Technologies/gensim/blob/f35faae7a7b0c3c8586fb61208560522e37e0e7e/setup.py#L347

I think the FuzzyTM dependency could be safely dropped, as the library is not actually imported. It would reduce the number of libraries Gensim pulls in and thus reduce the size of installations, including Docker images where minimal size is often required.

#### Versions

I'm using Ubuntu Linux 22.04.

Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Bits 64
NumPy 1.24.1
SciPy 1.10.0
gensim 4.3.0
FAST_VERSION 0

### PR DESCRIPTION
**Pull request by piskvorky**
Fixes #3423. Supersedes #3435, #3436.

This is still work-in-progress and needs finishing up. Namely:

1. Missing user-friendly docstrings and overall model motivation: what is this, who should use it? What do the various parameters mean?
2. As input, accept standard streaming corpora in the bag-of-words (BoW) format. Drop all the in-memory handling of the entire corpus in RAM as "list of list of strinks" and "scipy DOK matrix", that doesn't scale.
3. Complete the cleanup of the code formatting that I started. Especially use more helpful error messages in ValueErrors, showing what values are expected vs what the user supplied.
4. Related to that, focus all the parameter validation to a single place in code = the module entrypoints where users pass in these parameters. Currently the checks (even the same checks?) appear in multiple places, even in internal methods, where we should be in control of what the input values are, so we're doublechecking ourselves which makes no sense.

### CODE REVIEW

**Comment by piskvorky** [comment]
CC @ERijck are you able to continue and finish this up?

All the points above plus all the `FIXME` notes I left in the code must be resolved, if we are to keep FlsaModel in Gensim.

**Comment by ERijck** [comment]
@piskvorky yes, I will do that.

**Comment by piskvorky** [comment]
Finishing up 1, 3 and 4 will be a great start. I can then assist with 2 (input streaming), to bring flsamodel in line with the rest of Gensim.

**Comment by ERijck** [comment]
To get up to speed with Git, I followed the Codecademy Git&Github pro course today. Afterwards, I just tried to fetch and merge the work in your branch. To do so, I used the following:

image

I assumed to see your code when opening `flsamodel.py`. However, this is not the case. Then, I tried the following steps:

image

This does not work. Which command can I use to pull `cbfd972257f83d2d64803059e6585c00184f784c        refs/heads/flsa_fixes`?

**Comment by piskvorky** [comment]
Yeah `git` can be frustrating when you're starting out.

Probably best to discard any existing mess in your local fork and start fresh:

```bash
git checkout develop && git fetch upstream && git reset --hard upstream/develop  # discard local changes in your develop branch, if any.
git branch -D flsa_fixes  # delete your existing local flsa_fixes branch, if any.
git checkout -b my_flsa_fixes  # create a new local branch for your changes, named "my_flsa_fixes"
git reset --hard upstream/flsa_fixes  # set the content of "my_flsa_fixes" to match the remote "flsa_fixes", to begin with.
```

At that point you should be at commit `cbfd97225` on branch `my_flsa_fixes` so you can make your changes and commit them and push them to your Github firk repo.

When your changes are ready for review, open a new pull request (PR) from your `my_flsa_fixes` branch against Gensim's `flsa_fixes` branch.

Let me know how it goes :)

**Comment by ERijck** [comment]
Thank you @piskvorky, I will follow your steps!

**Comment by victox5** [comment]
Hi guys,

I have been checking licensing in some of my projects and I got `FuzzyTM`+`pyFUME` popping up in one using `gensim`. If correctly, they are following GPL, importing them in gensim would make gensim GPL as well, rather than LGPL. 

Are you aware of this? If I'm wrong concerning the licensing, please let me know.

Thanks!

**Comment by damonmerrill** [comment]
Plus, FuzzyTM is a GPL2/3 license which has a strong copy left requirement. Recently we let poetry update all our dependencies and our corporate scan tool reported a high concern to us with the dependency scan. We would not be able to continue to use Gensim if that library stayed in (I believe this would be the case for most companies/organizations where their IP is in software.)

**Comment by piskvorky** [comment]
Gensim has a strong copy left license too – LGPL. I'm afraid corporate concerns are not our primary concern when choosing dependencies.

We offer a commercial (paid) license for such cases.

**Comment by damonmerrill** [comment]
ahh, thanks for the clarification. A mis-understanding on my part with gensims (RaRe-Technologies). The company I work for would gladly purchase commercial licensing as needed.

**Comment by piskvorky** [comment]
@damonmerrill that would be great – we welcome contributions of all levels: https://github.com/sponsors/piskvorky

**Comment by pabs3** [comment]
I note that the license link in the file points at LGPLv3 instead of LGPLv2.1, that should get updated.

**Comment by piskvorky** [comment]
@ERijck can you please fix the merge conflict & update the LGPL link as per @pabs3 's comment above? Thanks.

**Comment by ERijck** [comment]
Yes, I will do this tomorrow!

**Comment by ERijck** [comment]
See PR #3471 where I apply the required changes to flsa_fixes

**Comment by mpenkov** [comment]
We don't have the bandwidth to keep pushing this along.

**Pull request closed without merging**
